CShop/Controllers/CategoryController.cs
using Data;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class CategoryController : Controller
    {
        MyUnitOfWork unit = MyUnitOfWork.Instance;


        public PartialViewResult List()
        {
            ViewBag.Categories  = unit.Categories.GetAll().Where(t=>t.Status);
            ViewBag.Publishers = unit.Publishers.GetAll().Where(t => t.Status);
            ViewBag.Products = unit.Products.GetAll().Where(t => t.Status);
            return PartialView("CategoriesListPartial");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }



    }
}

CShop/Controllers/ContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class ContactController : Controller
    {
        //
        // GET: /Contact/

        public ActionResult Index()
        {
            return View();
        }

    }
}

CShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.IO;
using System.Data;
using PagedList;
using Data;
using WebApplication1.ModelsTest;

namespace WebApplication1.Controllers
{
    public class ProductController : Controller
    {
        IUnitOfWork unit = MyUnitOfWork.Instance;

        //
        // GET: /Product/
        public ActionResult Index()
        {
            var products = unit.Products.GetAll().Where(t => t.Status);
            return View(products.ToList());
        }

        //
        // GET: /Product/Details/5
        public ActionResult Details(int? id, int? page)
        {
            if (id != null)
            {
                var product = unit.Products.GetById(id.Value);
                if (product == null)
                {
                    return HttpNotFound();
                }
                // tăng số lượt xem 
                product.TimeAccess += 1;
                unit.Products.Update(product);
                unit.Commit();

                // lấy danh sách comment và cho vào ViewBag
                var comments = unit.Comments.GetByProductId(id.Value);
                comments = comments.OrderByDescending(cm => cm.Id);

                // phân trang comment
                int currentPageIndex = page.HasValue ? page.Value : 1;
                ViewBag.Comments = comments.ToPagedList(currentPageIndex, 4);

                //related products
                var relatedProducts = unit.Products.GetRelatedProduct(id.Value);
                ViewBag.RelateProducts = relatedProducts;

                return View(product);
            }
            return HttpNotFound();
        }

        // GET: /Search/
        public ActionResult Search(String Name, int? Price, int? Category, int? Publisher, int? Page)
        {
            var Prices = new[]
             {
                new { Id = 1, Name = "Dưới 2 triệu" },
                new { Id = 2, Name = "Từ 2 triệu đến 4 triệu" },
                new { Id = 3, Name = "Từ 4 triệu đến 6 triệu" },
                 new { Id = 4, Name = "Trên 6 triệu" }
    
             };

            ViewBag.Prices = Prices;
            ViewBag.Categories = unit.Categories.GetAll().Where(t => t.Status).ToList();
            ViewBag.Publishers = unit.Publishers.GetAll().Where(t => t.Status).ToList();

            ViewBag.Name = Name;
            ViewBag.Price = Price;
            ViewBag.Category = Category;
            ViewBag.Publisher = Publisher;

            var products = unit.Products.GetAll().Where(t => t.Status);

            // Tìm kiếm theo tên
            if (!String.IsNullOrEmpty(Name))
            {
                products = from p in products
                           where p.Name.Contains(Name)
                           select p;
            }

            // Tìm kiếm theo mức giá
            if (Price != null)
            {
                switch (Price)
                {
                    case 1:
                        products = from p in products
                                   where p.Cost < 2000000
                                   select p;
                        break;
                    case 2:
                        products = from p in products
                                   where (p.Cost <= 4000000) && (p.Cost >= 2000000)
                                   select p;
                        break;
                    case 3:
                        products = from p in products
                                   where (p.Cost <= 6000000) && (p.Cost >= 4000000)
                                   select p;
                        break;
                    case 4:
                        products = from p in products
                                   where (p.Cost > 6000000)
                                   select p;
                        break;
                }
            }

            // Tìm kiếm theo Loại sản phẩm
            if (Category != null)
            {
                int id = Category.Value;
                products = from p in products
                           where p.CategoryId.Equals(id) || id == -1
                           select p;
            }

            // Tìm kiếm theo Nhà sản xuất
            if (Publisher != null)
            {
                int id = Publisher.Value;
                products = from p in products
                           where p.PublisherId.Equals(id)
                           select p;
            }
            products = products.OrderBy((p) => p.Cost);

            //Phan trang
            return View("Search", unit.Products.Paginate(Page, Global.Constants.NumItemOfPage, products));
        }

        public PartialViewResult HotProduct()
        {
            return PartialView("HotProductPartial", unit.Products.GetAllHot(Global.Constants.MaxHotProduct).Where(t => t.Status));
        }


        //public ActionResult ViewByType(string id, string sortOrder)
        //{
        //    var type = from p in unit.Products.GetAll()
        //               select p;


        //    if (!String.IsNullOrEmpty(id))
        //    {
        //        int idx = int.Parse(id);
        //        type = from p in unit.Products.GetAll()
        //               where p.CategoryId == idx
        //               select p;
        //    }

        //    ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
        //    ViewBag.CostSortParm = sortOrder == "Cost" ? "Cost_desc" : "Cost";
        //    ViewBag.StatusSortParm = sortOrder == "Status" ? "Status_desc" : "Status";

        //    switch (sortOrder)
        //    {
        //        case "name_desc":
        //            type = type.OrderByDescending(s => s.Name);
        //            break;
        //        case "Cost":
        //            type = type.OrderBy(s => s.Cost);
        //            break;
        //        case "Cost_desc":
        //            type = type.OrderByDescending(s => s.Cost);
        //            break;
        //        case "Status":
        //            type = type.OrderBy(s => s.Status);
        //            break;
        //        case "Status_desc":
        //            type = type.OrderByDescending(s => s.Status);
        //            break;

        //        default:
        //            type = type.OrderBy(s => s.Name);
        //            break;
        //    }

        //    return View("Index",type.ToList());
        //}


        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

CShop/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Data;
using WebApplication1.ModelsTest;
using System.Web.ModelBinding;

namespace WebApplication1.Controllers
{
    public class ShoppingCartController : Controller
    {
        MyUnitOfWork unit = MyUnitOfWork.Instance;
        
        //
        // GET: /ShopCart/
        public ActionResult Index(int? status)
        {
            List<ShoppingCartViewModels> models = new List<ShoppingCartViewModels>() ;
            var cart = unit.Carts.GetByHttpContext();

            var cartProducts = from cm in unit.CartProducts.GetAll()
                               where cm.CartId == cart.Id
                                select cm;
            foreach(CartProduct cartProduct in cartProducts)
            {
                ShoppingCartViewModels model = new ShoppingCartViewModels();
               
                model.ImageURL = cartProduct.Product.Image;
                model.Cost = cartProduct.Product.Cost;
                model.ProductName = cartProduct.Product.Name;
                model.TotalCost = cartProduct.ProductQuantity * cartProduct.Product.Cost;
                model.ProductQuantity = cartProduct.ProductQuantity;
                model.ProductId = cartProduct.ProductId;
                model.Category = cartProduct.Product.Category.Name.ToString();
                models.Add(model);
            }

            if (status != null)
            {
                if (status.Value == 1)
                    ViewBag.Mess = "Đã xóa sản phẩm khỏi giỏ hàng!";
                else
                    ViewBag.Mess = "Đã xảy ra lỗi!";
            }
            return View(models);
        }

        [HttpPost]
        public JsonResult AddToCart(int? productid, int? quantity)
        {
            if (productid != null && quantity > 0)
            {
                //var a = HttpContext.Session["123"];
                //var b = System.Web.HttpContext.Current.Session;
                if (unit.Products.AddToCart(
                                        productid.Value, 
                                        unit.Carts.GetByHttpContext().Id, 
                                        quantity.Value) == 0)
                    return Json(new { Error = "", Success = "Thay đổi số lượng thành công" });
                unit.Commit();
                return Json(new { Error = "" , Success = "Thêm vào giỏ hàng thành công"});
            }
            else if(quantity <= 0)
                return Json(new { Error = "Vui lòng nhập số lượng lớn hơn 0" });
            else if(quantity == null)
                return Json(new { Error = "Vui lòng nhập lại số lượng" });

            return Json(new { Error = "Product Id is null" });

        }

        [HttpPost]
        public ActionResult RemoveFromCart(int? productid)
        {
            if (productid != null)
            {
                //var product = db.Products.Find(productid);
                //var cart = ShoppingCartClass.GetCart(this.HttpContext);
                //cart.RemoveProductFromCart(product) ;

                unit.Carts.RemoveProductFromCart(unit.Carts.GetByHttpContext().Id, productid.Value);
                unit.Commit();
                return RedirectToAction("Index", new { status = 1 });
            }

            return RedirectToAction("Index", new { status = 0 });

        }

        [Authorize]
        public ActionResult Order ()
        {
            //var cart = ShoppingCartClass.GetCart(this.HttpContext);
            //ApplicationUser user = db.Users.Find(User.Identity.GetUserId());
            //cart.MigrateCart(user);

            unit.Carts.MigrateCart(unit.Carts.GetByHttpContext().Id, User.Identity.GetUserId());
            unit.Commit();
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Order(OrderViewModels model)
        {

            var cart = unit.Carts.GetByHttpContext();
            var currentid = User.Identity.GetUserId();
            ApplicationUser user = unit.Users.GetAll().FirstOrDefault(t=>t.Id==currentid);
            
            //cart.CreateOrder(model,user);
          
            if(ModelState.IsValid)
            { 
            var o = new Order { 
                DateOrder = DateTime.Now,
                IsOrdered = false,
                Notes = model.Notes,
                ReceiverAddress = model.ReceiverAddress,
                ReceiverName = model.ReceiverName,
                ReceiverPhone = model.ReceiverPhone,
                UserId = User.Identity.GetUserId()
            };
            unit.Orders.Add(o);
            unit.Commit();
            unit.Orders.OrderCart(o.Id, cart.Id);
      
            unit.Commit();

            return RedirectToAction("ConfirmOrder");
            }
            else
            {
                return View();
            }
        }

                [Authorize]

        public ActionResult ConfirmOrder ()
        {
            var currentid = User.Identity.GetUserId();

            ApplicationUser user = unit.Users.GetAll().FirstOrDefault(t => t.Id == currentid);
            ViewBag.User = user;

            var order = from or in unit.Orders.GetAll()
                          where or.User.Id == user.Id && or.IsOrdered == false
                          select or;
            order = order.OrderByDescending(or => or.Id);
            ViewBag.Order = order.FirstOrDefault();
                    

            List<Product> products = new List<Product>();
            var productInOrder = from p in unit.OrderProducts.GetAll()
                                 where p.Order.Id == order.FirstOrDefault().Id
                                 select p;
            List<int> productquantitys = new List<int>();
            foreach(OrderProduct p in productInOrder)
            {
                
                products.Add(p.Product);
                productquantitys.Add(p.ProductQuantity);
            }
          
            ViewBag.Products = products;
            ViewBag.ProductsQuantity = productquantitys;
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult ConfirmOrder (int? orderId)
        {
            var cart = unit.Carts.GetByHttpContext();

            Order order = unit.Orders.GetAll().FirstOrDefault(or => or.Id == orderId);
            order.IsOrdered = true;       
            TempData["msg"] = "<script>alert('Đã xác nhận đơn hàng thành công!');</script>";
            //unit.Carts.ClearProducts(cart.Id);
            unit.Carts.ClearProducts(cart.Id);
            unit.Commit();
            return RedirectToAction("ShoppingHistory");
        }

        [Authorize]
        public ActionResult ShoppingHistory ()
        {

            ApplicationUser user = unit.Users.Current;
            ViewBag.User = user;

            ShoppingHistory shoppingHistory = new ModelsTest.ShoppingHistory();
            shoppingHistory.orders = new List<OrderModels>();

            var order = from or in unit.Orders.GetAll()
                        where or.User.Id == user.Id && or.IsOrdered == true
                        select or;

            foreach (Order or in order)
            {

                OrderModels orderModel = new OrderModels();
                orderModel.products = new List<Product>();
                orderModel.productQuantitys = new List<int>();
                orderModel.order = or;

                var productInOrder = from p in unit.OrderProducts.GetAll()
                                     where p.Order.Id == or.Id
                                     select p;
                foreach (OrderProduct p in productInOrder)
                {
                    Product product = unit.Products.GetById(p.ProductId);
                    orderModel.products.Add(product);
                    orderModel.productQuantitys.Add(p.ProductQuantity);
                   
                }
                shoppingHistory.orders.Add(orderModel);
            }
            return View(shoppingHistory);
        }
	}
}

CShop/Views/Shared/CategoriesListPartial.cshtml
@using WebApplication1.ModelsTest

<div id="cat-product" class="left-box">
    <div class="cat-head">Danh mục sản phẩm</div><!-- catogory title -->
    <div class="details">
        <ul class='cat-1'>
            @{
                var Categories = ViewBag.Categories as IEnumerable<Category>;
                var Publishers = ViewBag.Publishers as IEnumerable<Publisher>;
                var Products = ViewBag.Products as IEnumerable<Product>;

                foreach (var c in Categories)
                {
                    bool haschild = c.Products.Any(t => Publishers.Contains(t.Publisher));
                    <li class="has-child">
                        <a href='@Url.Action("Search","Product",new {Category=@c.Id})'>@c.Name</a>
                        <ul class="cat-2">
                            @foreach (var pub in Publishers)
                            {
                                if(pub.Products.Count>0)
                                { 
                                    <li>
                                        <a href='@Url.Action("Search", "Product", new { Category = @c.Id, Publisher=@pub.Id })'>@pub.Name</a>                                      
                                    </li>
                                }
                            }
                        </ul>
                    </li>
                }
            }

        </ul>
    </div><!-- details -->
</div>

CShop/Views/Shared/HotProductPartial.cshtml
@model  IQueryable<WebApplication1.ModelsTest.Product>

<div id="popular-product" class="left-box">
    <div class="cat-head">Sản phẩm Hot</div><!-- catogory title -->
    <div class="details">
        @if (Model.Count() == 0)
        {
            <div class="hot-product">
                Không tìm thấy
            </div>
        }
        @foreach (var p in Model)
        {
            <a href='@Url.Action("Details", "Product", new{Id=@p.Id,area=""})'>
                <div class='hot-product'>
                    <img src='@Url.Content("~" + @p.Image)' />
                    <div class='hot-product-name'>@p.Name</div>
                    <div class='hot-product-price'>@p.Cost.ToString("##,#") VND</div>
                </div>
            </a>
            
        }

    </div><!-- details -->
</div>

CShop/Views/Shared/_Layout.cshtml
<!DOCTYPE>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@ViewBag.Title</title>


    @Styles.Render("~/css/bootstrap")
    @Styles.Render("~/css/mystyles")
    @Scripts.Render("~/script/jquery")
    @Scripts.Render("~/script/bootstrap")
    @Scripts.Render("~/script/myscripts")
    @RenderSection("Styles", false)
    
</head>
<body>
    @Html.Raw(TempData["msg"])
    <div id="container">
        <!-- begin header -->
        <div id="header">
            
            <div class="navigations">
                <div id="cart" class="navigation">
                    <a href='@Url.Action("Index", "ShoppingCart")'>
                        <img src="~/images/icon_cart.png" />
                        <div>Giỏ hàng</div>
                    </a>
                </div>
                <div id="contact" class="navigation">

                    <a href='@Url.Action("Index", "Contact")'>
                        <img src="~/images/icon_contact.png" />
                        <div>Liên hệ</div>
                    </a>
                </div>
                <div id="search" class="navigation">
                    <a href='@Url.Action("Search", "Product")'>
                        <img src="~/images/icon_search.png" />
                        <div>Tìm kiếm</div>
                    </a>
                </div>
                <div id="home" class="navigation">
                    <a href="@Url.Action("Index","Home")">
                        <img src="~/images/icon_home.png" />
                        <div>Trang chủ</div>
                    </a>
                </div>
                @Html.Partial("_LoginPartial")

                
            </div>
        </div>
        <!-- end header -->
        <!-- begin menu-and-support -->
        <div id="menu-and-support">
            <!-- begin wrapper menu -->
            <div id="top-menu" class="wrapper-menu">
                <ul>
                    <li><a href='@Url.Action("Index","Home")'>Trang chủ</a></li>
                    <li >
                        <a href='@Url.Action("Index","Home")'>Sản phẩm mới</a>
                    </li>
                    <li><a href='@Url.Action("Index", "Home")'>Sản phẩm hot</a></li>
                    <li><a href='@Url.Action("Index", "ShoppingCart")'>Giỏ hàng</a></li>
                    <li><a href='@Url.Action("Index", "Contact")'>Liên hệ</a></li>
                </ul>
            </div>
            <!-- end wrapper menu -->
            <div id="support">
                <div id='supporter-1' class='supporter'>
                    <img src="~/images/yahoo_on.png" />
                    <div class='desc'>Kỹ thuật 1 (0908989911)</div>
                </div>
                <div id='supporter-2' class='supporter'>
                    <img src="~/images/yahoo_on.png" />
                    <div class='desc'>Kỹ thuật 2 (0908989911)</div>
                </div>
                <div id='supporter-3' class='supporter'>
                    <img src="~/images/yahoo_off.png" />
                    <div class='desc'>Kỹ thuật 3 (0908989911)</div>
                </div>
                <div id='supporter-4' class='supporter'>
                    <img src="~/images/yahoo_on.png" />
                    <div class='desc'>Chăm sóc khách hàng 1 (0908989911)</div>
                </div>
                <div id='supporter-5' class='supporter'>
                    <img src="~/images/yahoo_off.png" />
                    <div class='desc'>Chăm sóc khách hàng 2 (0908989911)</div>
                </div>
                <div id='supporter-6' class='supporter'>
                    <img src="~/images/yahoo_off.png" />
                    <div class='desc'>Chăm sóc khách hàng 3 (0908989911)</div>
                </div>
                <form id="quick-search" action="~/Product/Search" method="get">
                    <input type="text" id='search-input' name='Name' placeholder='Tìm kiếm...' />
                </form>
                    <img id="search-img" src="~/images/search.png" />
                    <img id='call-img' src="~/images/call_icon.png" />
                    <span id='support-phone'>090.8989.936</span>
</div><!-- support -->
        </div><!-- end menu-and-support-->

        <!-- begin content -->
        <div id="content">

            <!-- begin left content -->
            <div id="left-content">
                <!-- category product -->
                @Html.Action("List", "Category", new { area = "" })
                <!-- popular-product-->
                @Html.Action("HotProduct", "Product", new { area = "" })
            </div>
            <!-- end left content -->
            <!-- begin right content -->
            <div id="right-content">
                <!-- =================================== Thêm phần mới tại đây =========================== -->
                @RenderBody()
            </div>
            <!-- end right content -->

        </div><!-- end content-->
        <!-- begin footer -->
        <div id="footer">
            <div id='footer-logo'></div>
            <div id='partners'>
                <p><b>Đối tác</b></p>
                <img src='~/images/acer.jpg' />
                <img src='~/images/amd.jpg' />
                <img src='~/images/asrock.jpg' />
                <img src='~/images/asus.jpg' />
                <img src='~/images/gigabyte.jpg' />
                <img src='~/images/Intel.jpg' />
                <img src='~/images/kingston.jpg' />
                <img src='~/images/logitech.jpg' />
                <img src='~/images/nvidia.jpg' />
            </div>
            <div id='footer-contact'>
                <p><b>Liên hệ</b></p>
                <b>CÔNG TY TRÁCH NHIỆM 2 THÀNH VIÊN</b>
                <p>Địa chỉ: DHKHTN, Hồ Chí Minh</p>
                <p>VPGD: DHKHTN</p>
                <p>MSSV: 1112100 - 1112194</p>
                <p>DĐ: 0987.99.68.68/ 0913.526.260/</p>
                <p>0974.94.99.86/ 0946.68.99.66/ 0983.21.36.68</p>
                <p>Fax: 08.73046898</p>
                <p>Email: hoang4893@gmail.com</p>
            </div>
        </div><!-- end footer -->

    </div><!-- end container -->
</body>
@RenderSection("Scripts", false)


</html>

CShop/Views/Shared/_Login.cshtml
@{
    ViewBag.Title = "Log in";
}

<div >
    @using (Html.BeginForm("Login", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)

        <div class="form-group">
            <input type="text" id='email-input' class="form-control" name='Username' placeholder="Nhập username"></input>
        </div>
        <div class="form-group">
            <input type="password" id='pass-input' class="form-control" name='PassWord' placeholder="Nhập mật khẩu"></input>
        </div>
        <div class="form-group">
        <input type='submit' class="btn btn-danger form-control" value='Đăng nhập'></input>
    </div>
        <div class="form-group" >
            <input type="checkbox" name="RememberMe" id='remember-chkb' value="true"></input>
            Ghi nhớ
        </div>
    
        <div>
            <a href="@Url.Action("ForgotPassword","Account")">Quên mật khẩu rùi!</a>
        </div>

    }
</div>
@section Scripts {
    @Scripts.Render("~/script/jqueryval")
}