CShop/Areas/Admin/Controllers/OrderController.cs
using Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class OrderController : Controller
    {
        MyUnitOfWork unit = MyUnitOfWork.Instance;
        //
        // GET: /Admin/Order/
        public ActionResult Index(int? Page)
        {
            
            ViewBag.OrderProducts = unit.OrderProducts.GetAll();
            return View(unit.Orders.Paginate(Page, 10));
        }
	}
}

CShop/Areas/Admin/Controllers/PublisherController.cs
using Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class PublisherController : Controller
    {
        MyUnitOfWork unit = MyUnitOfWork.Instance;

        //
        // GET: /Admin/Publisher/
        public ActionResult Index()
        {
            return View(unit.Publishers.GetAll());
        }

        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Add(string Name, string Detail, bool Status)
        {
            try
            {
                unit.Publishers.Add(new ModelsTest.Publisher { Name = Name, Detail = Detail, Status = Status });
                unit.Commit();
                ViewBag.Mess = string.Format("Thêm thành công {0}", Name);
                return View();
            }
            catch (Exception)
            {
                ViewBag.Mess = string.Format("Thêm {0} thất bại", Name);
                return View();
            }            
        }

        public ActionResult Active(int Id)
        {
            try
            {
                unit.Publishers.Active(Id);
                unit.Commit();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }            
        }

        public ActionResult DeActive(int Id)
        {
            try
            {
                unit.Publishers.DeActive(Id);
                unit.Commit();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult Edit(int Id, string Name, string Detail)
        {
            try
            {
                unit.Publishers.Update(Id, Name, Detail);
                unit.Commit();
                return Json(new { error = "" });
            }
            catch (Exception)
            {
                return Json(new { error = "Đã xảy ra lỗi" });
            }
            

        }

	}
}

CShop/Controllers/CategoryController.cs
using Data;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication1.Controllers
{
    public class CategoryController : Controller
    {
        MyUnitOfWork unit = MyUnitOfWork.Instance;


        public PartialViewResult List()
        {
            ViewBag.Categories  = unit.Categories.GetAll().Where(t=>t.Status);
            ViewBag.Publishers = unit.Publishers.GetAll().Where(t => t.Status);
            ViewBag.Products = unit.Products.GetAll().Where(t => t.Status);
            return PartialView("CategoriesListPartial");
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }



    }
}

CShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using System.IO;
using System.Data;
using PagedList;
using Data;
using WebApplication1.ModelsTest;

namespace WebApplication1.Controllers
{
    public class ProductController : Controller
    {
        IUnitOfWork unit = MyUnitOfWork.Instance;

        //
        // GET: /Product/
        public ActionResult Index()
        {
            var products = unit.Products.GetAll().Where(t => t.Status);
            return View(products.ToList());
        }

        //
        // GET: /Product/Details/5
        public ActionResult Details(int? id, int? page)
        {
            if (id != null)
            {
                var product = unit.Products.GetById(id.Value);
                if (product == null)
                {
                    return HttpNotFound();
                }
                // tăng số lượt xem 
                product.TimeAccess += 1;
                unit.Products.Update(product);
                unit.Commit();

                // lấy danh sách comment và cho vào ViewBag
                var comments = unit.Comments.GetByProductId(id.Value);
                comments = comments.OrderByDescending(cm => cm.Id);

                // phân trang comment
                int currentPageIndex = page.HasValue ? page.Value : 1;
                ViewBag.Comments = comments.ToPagedList(currentPageIndex, 4);

                //related products
                var relatedProducts = unit.Products.GetRelatedProduct(id.Value);
                ViewBag.RelateProducts = relatedProducts;

                return View(product);
            }
            return HttpNotFound();
        }

        // GET: /Search/
        public ActionResult Search(String Name, int? Price, int? Category, int? Publisher, int? Page)
        {
            var Prices = new[]
             {
                new { Id = 1, Name = "Dưới 2 triệu" },
                new { Id = 2, Name = "Từ 2 triệu đến 4 triệu" },
                new { Id = 3, Name = "Từ 4 triệu đến 6 triệu" },
                 new { Id = 4, Name = "Trên 6 triệu" }
    
             };

            ViewBag.Prices = Prices;
            ViewBag.Categories = unit.Categories.GetAll().Where(t => t.Status).ToList();
            ViewBag.Publishers = unit.Publishers.GetAll().Where(t => t.Status).ToList();

            ViewBag.Name = Name;
            ViewBag.Price = Price;
            ViewBag.Category = Category;
            ViewBag.Publisher = Publisher;

            var products = unit.Products.GetAll().Where(t => t.Status);

            // Tìm kiếm theo tên
            if (!String.IsNullOrEmpty(Name))
            {
                products = from p in products
                           where p.Name.Contains(Name)
                           select p;
            }

            // Tìm kiếm theo mức giá
            if (Price != null)
            {
                switch (Price)
                {
                    case 1:
                        products = from p in products
                                   where p.Cost < 2000000
                                   select p;
                        break;
                    case 2:
                        products = from p in products
                                   where (p.Cost <= 4000000) && (p.Cost >= 2000000)
                                   select p;
                        break;
                    case 3:
                        products = from p in products
                                   where (p.Cost <= 6000000) && (p.Cost >= 4000000)
                                   select p;
                        break;
                    case 4:
                        products = from p in products
                                   where (p.Cost > 6000000)
                                   select p;
                        break;
                }
            }

            // Tìm kiếm theo Loại sản phẩm
            if (Category != null)
            {
                int id = Category.Value;
                products = from p in products
                           where p.CategoryId.Equals(id) || id == -1
                           select p;
            }

            // Tìm kiếm theo Nhà sản xuất
            if (Publisher != null)
            {
                int id = Publisher.Value;
                products = from p in products
                           where p.PublisherId.Equals(id)
                           select p;
            }
            products = products.OrderBy((p) => p.Cost);

            //Phan trang
            return View("Search", unit.Products.Paginate(Page, Global.Constants.NumItemOfPage, products));
        }

        public PartialViewResult HotProduct()
        {
            return PartialView("HotProductPartial", unit.Products.GetAllHot(Global.Constants.MaxHotProduct).Where(t => t.Status));
        }


        //public ActionResult ViewByType(string id, string sortOrder)
        //{
        //    var type = from p in unit.Products.GetAll()
        //               select p;


        //    if (!String.IsNullOrEmpty(id))
        //    {
        //        int idx = int.Parse(id);
        //        type = from p in unit.Products.GetAll()
        //               where p.CategoryId == idx
        //               select p;
        //    }

        //    ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
        //    ViewBag.CostSortParm = sortOrder == "Cost" ? "Cost_desc" : "Cost";
        //    ViewBag.StatusSortParm = sortOrder == "Status" ? "Status_desc" : "Status";

        //    switch (sortOrder)
        //    {
        //        case "name_desc":
        //            type = type.OrderByDescending(s => s.Name);
        //            break;
        //        case "Cost":
        //            type = type.OrderBy(s => s.Cost);
        //            break;
        //        case "Cost_desc":
        //            type = type.OrderByDescending(s => s.Cost);
        //            break;
        //        case "Status":
        //            type = type.OrderBy(s => s.Status);
        //            break;
        //        case "Status_desc":
        //            type = type.OrderByDescending(s => s.Status);
        //            break;

        //        default:
        //            type = type.OrderBy(s => s.Name);
        //            break;
        //    }

        //    return View("Index",type.ToList());
        //}


        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }
    }
}

CShop/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE>

<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>@ViewBag.Title</title>


    @Styles.Render("~/css/bootstrap")
    @Styles.Render("~/css/mystyles")
    @Scripts.Render("~/script/jquery")
    @Scripts.Render("~/script/bootstrap")
    @Scripts.Render("~/script/myscripts")
    @RenderSection("Styles", false)
    
</head>
<body>
    @Html.Raw(TempData["msg"])
    <div id="container">
        <!-- begin header -->
        <div id="header">
            <div id="logo"><img src="~/images/logo.png" /></div><!-- logo -->
            <div class="navigations">
                    
                <div id="cart" class="navigation">
                    <a href='@Url.Action("Index", "Account")'>
                        <img src="~/images/icon_cart.png" />
                        <div>Giỏ hàng</div>
                    </a>
                </div>
                <div id="contact" class="navigation">

                    <a href='@Url.Action("Index", "Account")'>
                        <img src="~/images/icon_contact.png" />
                        <div>Liên hệ</div>
                    </a>
                </div>
                <div id="search" class="navigation">
                    <a href='@Url.Action("Index", "Account")'>
                        <img src="~/images/icon_search.png" />
                        <div>Tìm kiếm</div>
                    </a>
                </div>
                <div id="home" class="navigation">
                    <a href="~/Home/Index">
                        <img src="~/images/icon_home.png" />
                        <div>Trang chủ</div>
                    </a>
                </div>
                @Html.Partial("_LoginPartial")

                
            </div>
        </div>
        <!-- end header -->
        <!-- begin menu-and-support -->
        <div id="menu-and-support">
            <!-- begin wrapper menu -->
            <div id="top-menu" class="wrapper-menu">
                <ul>
                    <li><a href='@Url.Action("Index","Account")'>Quản lý tài khoản</a></li>
                    <li class="has-child">
                        <a href='@Url.Action("Index","Category")'>Gian hàng</a>
                        <ul>
                            <a href="@Url.Action("ViewByType", "Product", new { id = "1"})"><li>CPU</li></a>
                            <a href="@Url.Action("ViewByType", "Product", new { id = "2"})"><li>Card màn hình</li></a>
                            <a href="@Url.Action("ViewByType", "Product", new { id = "3"})"><li>RAM</li></a>
                            <li>Mouse game</li>
                        </ul>
                    </li>
                    <li>
                        <a href='@Url.Action("Index","Publisher")'>Nhà phân phối</a>

                    </li>
                    <li><a href='@Url.Action("Index","Product")'>Sản phẩm</a></li>
                    <li><a href='@Url.Action("Index","Order")'>Đơn hàng</a></li>
                </ul>
            </div>
            <!-- end wrapper menu -->
            <div id="support">
                <div id='supporter-1' class='supporter'>
                    <img src="~/images/yahoo_on.png" />
                    <div class='desc'>Kỹ thuật 1 (0908989911)</div>
                </div>
                <div id='supporter-2' class='supporter'>
                    <img src="~/images/yahoo_on.png" />
                    <div class='desc'>Kỹ thuật 2 (0908989911)</div>
                </div>
                <div id='supporter-3' class='supporter'>
                    <img src="~/images/yahoo_off.png" />
                    <div class='desc'>Kỹ thuật 3 (0908989911)</div>
                </div>
                <div id='supporter-4' class='supporter'>
                    <img src="~/images/yahoo_on.png" />
                    <div class='desc'>Chăm sóc khách hàng 1 (0908989911)</div>
                </div>
                <div id='supporter-5' class='supporter'>
                    <img src="~/images/yahoo_off.png" />
                    <div class='desc'>Chăm sóc khách hàng 2 (0908989911)</div>
                </div>
                <div id='supporter-6' class='supporter'>
                    <img src="~/images/yahoo_off.png" />
                    <div class='desc'>Chăm sóc khách hàng 3 (0908989911)</div>
                </div>

                <form id="quick-search" action="~/Product/Search" method="get">
                    <input type="text" id='search-input' name='Name' placeholder='Tìm kiếm...' />
                </form>
                <img id="search-img" src="~/images/search.png" />
                <img id='call-img' src="~/images/call_icon.png" />
                <span id='support-phone'>090.8989.936</span>
            </div><!-- support -->
        </div><!-- end menu-and-support-->

        <!-- begin content -->
        <div id="content">

            <!-- begin left content -->
            <div id="left-content">
                <div id="cat-product" class="left-box">
                    <div class="cat-head">Danh mục sản phẩm</div><!-- catogory title -->
                  
                    </div><!-- details -->
                </div><!-- category product -->
                <!-- popular-product-->
                
            </div>
            <!-- end left content -->
            <!-- begin right content -->
            <div id="right-content">
                <!-- =================================== Thêm phần mới tại đây =========================== -->
                @RenderBody()
            </div>
            <!-- end right content -->

        </div><!-- end content-->
        <!-- begin footer -->
        <div id="footer">
            <div id='footer-logo'></div>
            <div id='partners'>
                <p><b>Đối tác</b></p>
                <img src='~/images/acer.jpg' />
                <img src='~/images/amd.jpg' />
                <img src='~/images/asrock.jpg' />
                <img src='~/images/asus.jpg' />
                <img src='~/images/gigabyte.jpg' />
                <img src='~/images/Intel.jpg' />
                <img src='~/images/kingston.jpg' />
                <img src='~/images/logitech.jpg' />
                <img src='~/images/nvidia.jpg' />
            </div>
            <div id='footer-contact'>
                <p><b>Liên hệ</b></p>
                <b>CÔNG TY TRÁCH NHIỆM 2 THÀNH VIÊN</b>
                <p>Địa chỉ: 135 Nam Kỳ Khởi Nghĩa, Bến Thành, Hồ Chí Minh</p>
                <p>VPGD: Số 4 Yên Bình, Phúc La, Hà Đông, Hà Nội</p>
                <p>Điện thoại: 04.35541904</p>
                <p>DĐ: 0987.99.68.68/ 0913.526.260/</p>
                <p>0974.94.99.86/ 0946.68.99.66/ 0983.21.36.68</p>
                <p>Fax: 04.73046898</p>
                <p>Email: haichangtrai@gmail.com</p>
            </div>
        </div><!-- end footer -->

    </div><!-- end container -->
</body>
@RenderSection("Scripts", false)


</html>