CShop/Areas/Admin/Controllers/ProductController.cs
using Data;
using Model.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.ModelsTest;

namespace WebApplication1.Areas.Admin.Controllers
{
   [Authorize(Roles = "Admin")]

    public class ProductController : Controller
    {
        MyUnitOfWork unit = MyUnitOfWork.Instance;

        //
        // GET: /Admin/Product/
        public ActionResult Index(int? Page, int? Category, int? Publisher, int? CostLevel)
        {
            if (Category == null)
                Category = TempData[Global.Constants.CategoryFilter] as int?;
            if (Publisher == null)
                Publisher = TempData[Global.Constants.PublisherFilter] as int?;
            if (CostLevel == null)
                CostLevel = TempData[Global.Constants.CostLeverFilter] as int?;
            if (Page == null)
                Page = TempData[Global.Constants.ProductPage] as int?;
            TempData[Global.Constants.CategoryFilter] = Category;
            TempData[Global.Constants.PublisherFilter] = Publisher;
            TempData[Global.Constants.CostLeverFilter] = CostLevel;
            TempData[Global.Constants.ProductPage] = Page;

            var tmp = unit.Products.Search(Category, Publisher, CostLevel);
            var p = tmp.FirstOrDefault();
            var result = unit.Products.Paginate(Page, 10, tmp);
            return View(result);
        }

        public ActionResult Add()
        {
            ViewBag.Categories = unit.Categories.GetAll();
            ViewBag.Publishers = unit.Publishers.GetAll();
            return View();
        }

        [HttpPost]
        public ActionResult Add(AddProductViewModel product, HttpPostedFileBase File)
        {
            try 
	        {
                unit.Products.Add(product, File);
                unit.Commit();
                ViewBag.Mess = string.Format("Thêm {0} thành công", product.Name);
	        }
	        catch (Exception ex)
	        {
                ViewBag.Mess = ex.Message;
	        }

            ViewBag.Categories = unit.Categories.GetAll();
            ViewBag.Publishers = unit.Publishers.GetAll();
            return View();
            
        }

        [HttpPost]
        public ActionResult Edit(int Id, string Name, double Cost, string Detail)
        {
            try
            {

                unit.Products.Update(Id, Name, Cost, Detail);
                unit.Commit();
                return Json(new { error = "" });
            }
            catch (Exception ex)
            {
                return Json(new { error = ex.Message });
            }
            
        }

        [HttpPost]
        public ActionResult UploadImage(int Id, HttpPostedFileBase Image)
        {
            try
            {
                unit.Products.Update(Id, Image);
                unit.Commit();
                return Json(new { error = ""});
            }
            catch (Exception ex)
            {
                return Json(new { error = ex.Message });
            }           
        }

        public ActionResult Active(int Id)
        {
            try
            {
                unit.Products.Active(Id);
                unit.Commit();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult DeActive(int Id)
        {
            try
            {
                unit.Products.DeActive(Id);
                unit.Commit();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
        }
	}
}

CShop/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Microsoft.AspNet.Identity;
using Data;
using WebApplication1.ModelsTest;


namespace WebApplication1.Controllers
{
    public class CommentController : Controller
    {
        MyUnitOfWork unit = MyUnitOfWork.Instance;
        //
        // GET: /Comment/

        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult Post(int? productid, string name, string content)
        {
            if (productid != null)
            {
                var comment = new Comment()
                {
                    Content = content,
                    DateCreated = DateTime.Now,
                    ProductId = productid.Value,
                    SenderName = name,
                    UserId = User.Identity.GetUserId(),
                    Status = true
                };              
                //db.Comments.Add(comment);
                //db.SaveChanges();
                unit.Comments.Add(comment);
                unit.Commit();
                
                return Json(new { Error = "", PostId = comment.Id });
            }

            return Json(new { Error = "ProductId is null" });
            
        }
        [Authorize]
        [HttpPost]
        public JsonResult Edit(int postid, string content)
        {
            var UserId = User.Identity.GetUserId();
            if (unit.Comments.GetAll().Any(t => t.Id == postid && t.UserId == UserId))
            {
                var c = unit.Comments.GetById(postid);
                if (c == null) return Json(new { error = "Not found" });
                c.Content = content;
                unit.Comments.Update(c);
                unit.Commit();
                return Json(new { Error = "" });
            }
            return Json(new { Error = "Khong duoc phep" });
            
            //var comment = db.Comments.FirstOrDefault(cm => cm.Id == postid);
            
            //if (comment != null)
            //{
            //    comment.Content = content;
            //    db.SaveChanges();
            //    return Json(new {Error=""});
            //}
            //return Json(new {Error="Not found" });
        }
        [Authorize(Roles="Admin")]
        [HttpPost]
        public JsonResult Delete(int postid)
        {
            var c = unit.Comments.GetById(postid);
            if (c == null) return Json(new { Error = "Not found" });
            unit.Comments.Delete(c);
            return Json(new { Error = "" });
        }

        [HttpPost]
        public ActionResult Paging(int? productid, int? page)
        {

            return RedirectToAction("Details", "Product", new {id = productid, page=page});
        }
    }
}

CShop/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Data;
using WebApplication1.ModelsTest;
using System.Web.ModelBinding;

namespace WebApplication1.Controllers
{
    public class ShoppingCartController : Controller
    {
        MyUnitOfWork unit = MyUnitOfWork.Instance;
        
        //
        // GET: /ShopCart/
        public ActionResult Index(int? status)
        {
            List<ShoppingCartViewModels> models = new List<ShoppingCartViewModels>() ;
            var cart = unit.Carts.GetByHttpContext();

            var cartProducts = from cm in unit.CartProducts.GetAll()
                               where cm.CartId == cart.Id
                                select cm;
            foreach(CartProduct cartProduct in cartProducts)
            {
                ShoppingCartViewModels model = new ShoppingCartViewModels();
               
                model.ImageURL = cartProduct.Product.Image;
                model.Cost = cartProduct.Product.Cost;
                model.ProductName = cartProduct.Product.Name;
                model.TotalCost = cartProduct.ProductQuantity * cartProduct.Product.Cost;
                model.ProductQuantity = cartProduct.ProductQuantity;
                model.ProductId = cartProduct.ProductId;
                model.Category = cartProduct.Product.Category.Name.ToString();
                models.Add(model);
            }

            if (status != null)
            {
                if (status.Value == 1)
                    ViewBag.Mess = "Đã xóa sản phẩm khỏi giỏ hàng!";
                else
                    ViewBag.Mess = "Đã xảy ra lỗi!";
            }
            return View(models);
        }

        [HttpPost]
        public JsonResult AddToCart(int? productid, int? quantity)
        {
            if (productid != null && quantity > 0)
            {
                //var a = HttpContext.Session["123"];
                //var b = System.Web.HttpContext.Current.Session;
                if (unit.Products.AddToCart(
                                        productid.Value, 
                                        unit.Carts.GetByHttpContext().Id, 
                                        quantity.Value) == 0)
                    return Json(new { Error = "", Success = "Thay đổi số lượng thành công" });
                unit.Commit();
                return Json(new { Error = "" , Success = "Thêm vào giỏ hàng thành công"});
            }
            else if(quantity <= 0)
                return Json(new { Error = "Vui lòng nhập số lượng lớn hơn 0" });
            else if(quantity == null)
                return Json(new { Error = "Vui lòng nhập lại số lượng" });

            return Json(new { Error = "Product Id is null" });

        }

        [HttpPost]
        public ActionResult RemoveFromCart(int? productid)
        {
            if (productid != null)
            {
                //var product = db.Products.Find(productid);
                //var cart = ShoppingCartClass.GetCart(this.HttpContext);
                //cart.RemoveProductFromCart(product) ;

                unit.Carts.RemoveProductFromCart(unit.Carts.GetByHttpContext().Id, productid.Value);
                unit.Commit();
                return RedirectToAction("Index", new { status = 1 });
            }

            return RedirectToAction("Index", new { status = 0 });

        }

        [Authorize]
        public ActionResult Order ()
        {
            //var cart = ShoppingCartClass.GetCart(this.HttpContext);
            //ApplicationUser user = db.Users.Find(User.Identity.GetUserId());
            //cart.MigrateCart(user);

            unit.Carts.MigrateCart(unit.Carts.GetByHttpContext().Id, User.Identity.GetUserId());
            unit.Commit();
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult Order(OrderViewModels model)
        {

            var cart = unit.Carts.GetByHttpContext();
            var currentid = User.Identity.GetUserId();
            ApplicationUser user = unit.Users.GetAll().FirstOrDefault(t=>t.Id==currentid);
            
            //cart.CreateOrder(model,user);
          
            if(ModelState.IsValid)
            { 
            var o = new Order { 
                DateOrder = DateTime.Now,
                IsOrdered = false,
                Notes = model.Notes,
                ReceiverAddress = model.ReceiverAddress,
                ReceiverName = model.ReceiverName,
                ReceiverPhone = model.ReceiverPhone,
                UserId = User.Identity.GetUserId()
            };
            unit.Orders.Add(o);
            unit.Commit();
            unit.Orders.OrderCart(o.Id, cart.Id);
      
            unit.Commit();

            return RedirectToAction("ConfirmOrder");
            }
            else
            {
                return View();
            }
        }

                [Authorize]

        public ActionResult ConfirmOrder ()
        {
            var currentid = User.Identity.GetUserId();

            ApplicationUser user = unit.Users.GetAll().FirstOrDefault(t => t.Id == currentid);
            ViewBag.User = user;

            var order = from or in unit.Orders.GetAll()
                          where or.User.Id == user.Id && or.IsOrdered == false
                          select or;
            order = order.OrderByDescending(or => or.Id);
            ViewBag.Order = order.FirstOrDefault();
                    

            List<Product> products = new List<Product>();
            var productInOrder = from p in unit.OrderProducts.GetAll()
                                 where p.Order.Id == order.FirstOrDefault().Id
                                 select p;
            List<int> productquantitys = new List<int>();
            foreach(OrderProduct p in productInOrder)
            {
                
                products.Add(p.Product);
                productquantitys.Add(p.ProductQuantity);
            }
          
            ViewBag.Products = products;
            ViewBag.ProductsQuantity = productquantitys;
            return View();
        }

        [HttpPost]
        [Authorize]
        public ActionResult ConfirmOrder (int? orderId)
        {
            var cart = unit.Carts.GetByHttpContext();

            Order order = unit.Orders.GetAll().FirstOrDefault(or => or.Id == orderId);
            order.IsOrdered = true;       
            TempData["msg"] = "<script>alert('Đã xác nhận đơn hàng thành công!');</script>";
            //unit.Carts.ClearProducts(cart.Id);
            unit.Carts.ClearProducts(cart.Id);
            unit.Commit();
            return RedirectToAction("ShoppingHistory");
        }

        [Authorize]
        public ActionResult ShoppingHistory ()
        {

            ApplicationUser user = unit.Users.Current;
            ViewBag.User = user;

            ShoppingHistory shoppingHistory = new ModelsTest.ShoppingHistory();
            shoppingHistory.orders = new List<OrderModels>();

            var order = from or in unit.Orders.GetAll()
                        where or.User.Id == user.Id && or.IsOrdered == true
                        select or;

            foreach (Order or in order)
            {

                OrderModels orderModel = new OrderModels();
                orderModel.products = new List<Product>();
                orderModel.productQuantitys = new List<int>();
                orderModel.order = or;

                var productInOrder = from p in unit.OrderProducts.GetAll()
                                     where p.Order.Id == or.Id
                                     select p;
                foreach (OrderProduct p in productInOrder)
                {
                    Product product = unit.Products.GetById(p.ProductId);
                    orderModel.products.Add(product);
                    orderModel.productQuantitys.Add(p.ProductQuantity);
                   
                }
                shoppingHistory.orders.Add(orderModel);
            }
            return View(shoppingHistory);
        }
	}
}

CShop/Views/Product/Create.cshtml
@model WebApplication1.ModelsTest.Product

@{
    ViewBag.Title = "Create";
}
@section Styles{
<link href="~/Content/product.css" rel="stylesheet" />
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

@using (Html.BeginForm("Create", "Product", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)


        <fieldset class="create-field">
            <legend class="title-field">Thêm sản phẩm</legend>

            <div class="editor-field">
                <label>Tên sản phẩm</label>
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>

            <div class="editor-field">
                <label>Giá</label>

                @Html.EditorFor(model => model.Cost)
                @Html.ValidationMessageFor(model => model.Cost)

            </div>

            <div class="editor-field">
                <label>Chi tiết</label>

                @Html.EditorFor(model => model.Detail)
                @Html.ValidationMessageFor(model => model.Detail)

            </div>
            <div class="editor-field">
                <label>Tình trạng </label>

                @Html.EditorFor(model => model.Status)
                @Html.ValidationMessageFor(model => model.Status)
            </div>

            <div class="editor-field">
                <label>Loại sản phẩm</label>
                @Html.DropDownList("CategoryId", String.Empty)
                @Html.ValidationMessageFor(model => model.CategoryId)
            </div>

            <div class="editor-field">
                <label>Nhà sản xuất</label>
                @Html.DropDownList("PublisherId", String.Empty)
                @Html.ValidationMessageFor(model => model.PublisherId)
            </div>
            <div class="editor-field">
                <label>Hình ảnh</label>
                <input type="file" name="file" />
            </div>
            <div class="button-field">               
                <input type="submit" value="Thêm sản phẩm" id=submit />
            </div>


        </fieldset>
                <p>
                @Html.ActionLink("Quay lại trang quản lý", "Index")
            </p>
}

CShop/Views/Product/Delete.cshtml
@model WebApplication1.ModelsTest.Product

@{
    ViewBag.Title = "Delete";
}

@section Styles{
    <link href="~/Content/category.css" rel="stylesheet" />
    <link href="~/Content/product.css" rel="stylesheet" type="text/css" />
}

<h2>Bạn có chắc rằng bạn muốn xóa?</h2>
    <fieldset class="create-field">
        <legend>Xóa sản phẩm</legend>

        <div class="editor-field">
            <label>Tên sản phẩm</label>
            @Html.DisplayFor(model => model.Name)
        </div>

        <div class="editor-field">
            <label>Giá</label>

            @Html.DisplayFor(model => model.Cost)
        </div>

        <div class="editor-field">
            <label>Chi tiết</label>

            @Html.DisplayFor(model => model.Detail)
        </div>
        <div class="editor-field">
            <label>Tình trạng </label>

            @Html.DisplayFor(model => model.Status)
        </div>

        <div class="editor-field">
            <label>Loại sản phẩm</label>
            @Html.DisplayFor(model => model.Category.Name)
        </div>

        <div class="editor-field">
            <label>Nhà sản xuất</label>
            @Html.DisplayFor(model => model.Publisher.Name)
        </div>
        
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
    <p class="button-field">

        <input type="submit" value="Xóa sản phẩm" />
       
    </p>
        }
    </fieldset>
<div class="back-function">
    @Html.ActionLink("Quay trở lại trang quản lý", "Index")
</div>

CShop/Views/Product/Detail.cshtml
@{
    ViewBag.Title = "Detail";
}
@section Styles{
<link href="~/Content/product-detail.css" rel="stylesheet" />
}
@section Scripts{
<script src="~/Scripts/product-detail.js"></script>
}

<div id="detail-category">
    <span id="image-category">
        <img src="../images/CPU/pentium_dual_core_g2030_big.jpg" />
    </span>
    <div id="name-category">CPU Intel Pentium Dual Core G2030</div>
    <div class="category-status"> <span class="brown-color"> Tình trạng : </span> <span class="orange-color"> Có hàng </span> </div>
    <div class="category-status"><span class="brown-color">Chi tiết: </span>3.0Ghz , 3Mb cache,Box </div>
    <div class="category-status" id="cost-category">Giá bán: 1.240.000 VNĐ</div>
    <div class="category-status">
        <div class="button">MUA NGAY</div>
    </div>

    <div class="ship">
        <div id="support-tranport">
            <img src="../images/small-truck.png" />
            <span>
                GIAO HÀNG LÊN TỚI 150KM:
            </span>
        </div>
        <ul class="ship-content">
            <li>Khung giờ giao hàng từ 8h - 20h hàng ngày.</li>
            <li>Nhận hàng trong 12h tại Hà Nội và TPHCM.</li>
            <li>Bảo hành chính hãng.</li>
        </ul>
    </div>
</div>

<div id="comment-box-content">
    <h2>Bình luận </h2>

    <input id="comment-name" placeholder="Name!" type="text" name="comment-name"> </input>
    <textarea id="comment-area" placeholder="Enter your comment here!" cols="100%" rows="4" name="comment-area"></textarea>
    <button data-url='@Url.Action("","Comment")' id="button-comment" name="button-comment" value="Post comment">Post comment </button>
    <p id="error-messeage"> </p>
    <div id="list-comment">Danh sách bình luận </div>
    
    @if (ViewBag.Comments != null){
        <div>I'm here</div>
        foreach (var cm in ViewBag.Comments)
        {
            <div class="comment-box-username">UserId: @cm.UserId</div>
            <div class="comment-box-text">@cm.Content</div>
            <div class='comment-function-edit'>Sửa</div>
            <div class='comment-function-delete'>Xóa</div>
        }
    }
    else{
        <div>I'm here</div>
    }
    
    
</div>      

CShop/Views/Product/Details.cshtml
@model WebApplication1.ModelsTest.Product
@using MvcPaging
@{
    ViewBag.Title = "Details";
}
@section Styles{
    <link href="~/Content/product-detail.css" rel="stylesheet" />
}

@section Scripts{
    <script src="~/Scripts/product-detail.js"></script>
}



<div id="detail-category">
    <p id="erroMess-cart"></p>
    <span id="image-category">
        <img src='@Url.Content("~" + @Model.Image)' />
    </span>
    

    <div class="product-right-content">
        <div id="name-category">@Model.Name</div>

        <div class="category-status">
            <span class="brown-color"> Tình trạng : </span>
            <span class="orange-color">
                @if (Model.Status)
                { <span>Còn hàng</span> }
                else
                { <span>Hết hàng</span> }
            </span>
        </div>
        <div class="category-status">
            <span class="brown-color">Chi tiết: </span>@Model.Detail
        </div>
        <div class="category-status" id="cost-category">Giá bán: @Model.Cost VNĐ</div>
        <div class="category-status">
            <span>Số lượng</span>
            <input type="text" id="quantity" value="1" />
            <div class="button-add" data-url='@Url.Action("","ShoppingCart")'>THÊM VÀO GIỎ</div>
        </div>
        <div class="category-status">
            <p>Số lượt xem: @Model.TimeAccess</p>
        </div>

        <div class="ship">
            <div id="support-tranport">
                <img src="~/images/small-truck.png" />
                <span>
                    GIAO HÀNG LÊN TỚI 150KM:
                </span>
            </div>
            <ul class="ship-content">
                <li>Khung giờ giao hàng từ 8h - 20h hàng ngày.</li>
                <li>Nhận hàng trong 12h tại Hà Nội và TPHCM.</li>
                <li>Bảo hành chính hãng.</li>
            </ul>
        </div>

    </div>
</div>
<div id='new-products'>
    <h3>Sản phẩm liên quan</h3>
    @foreach (var p in ViewBag.RelateProducts)
    {
        <a href="@Url.Action("Details","Product", new {Id=@p.Id})">
            <div class='product'>
                <img src='@Url.Content("~" + @p.Image)' />
                <div class='name-product'>@p.Name</div>
                <div class='price-product'>@p.Cost VND</div>
            </div>
        </a>
    }

</div>



<div id="comment-box-content" data-productid="@Model.Id">
    <h2>Bình luận </h2>
    @{
        if (Request.IsAuthenticated)
        {
            <input id="comment-name" placeholder="Name!" type="text" name="comment-name" disabled ="disabled" value="@User.Identity.Name">
        }
        else
        {
            <input id="comment-name" placeholder="Name!" type="text" name="comment-name">
        }
    }
    
    <textarea id="comment-area" placeholder="Enter your comment here!" cols="100%" rows="4" name="comment-area"></textarea>
    <button data-url='@Url.Action("","Comment")' id="button-comment" name="button-comment" value="Post comment">Post comment </button>
    <p id="error-messeage"> </p>

        <div id="list-comment">
            <div class="title">Danh sách bình luận</div>

         
            
            @{Html.RenderPartial("PagingPartial");}

        </div>
    
    @*End List-comment*@

    <script type="text/javascript">

        function beginPaging(args) {
            // Animate
            $('#list-comment').fadeOut('normal');
        }

        function successPaging() {
            // Animate
            $('#list-comment').fadeIn('normal');
            $('a').tooltip();
        }

        function failurePaging() {
            alert("Could not retrieve list.");
        }

    </script>

</div>

CShop/Views/Product/Edit.cshtml
@model WebApplication1.ModelsTest.Product

@{
    ViewBag.Title = "Edit";
}
@section Styles{
<link href="~/Content/product.css" rel="stylesheet" />
}

@using (Html.BeginForm("Edit", "Product", FormMethod.Post, new { enctype = "multipart/form-data" })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

        <fieldset class="create-field">
            <legend class="title-field">Sửa sản phẩm</legend>

            <div class="editor-field">
                <label>Tên sản phẩm</label>
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>

            <div class="editor-field">
                <label>Giá</label>

                @Html.EditorFor(model => model.Cost)
                @Html.ValidationMessageFor(model => model.Cost)

            </div>

            <div class="editor-field">
                <label>Chi tiết</label>

                @Html.EditorFor(model => model.Detail)
                @Html.ValidationMessageFor(model => model.Detail)

            </div>
            <div class="editor-field">
                <label>Tình trạng </label>

                @Html.EditorFor(model => model.Status)
                @Html.ValidationMessageFor(model => model.Status)
            </div>

            <div class="editor-field">
                <label>Loại sản phẩm</label>
                @Html.DropDownList("CategoryId", String.Empty)
                @Html.ValidationMessageFor(model => model.CategoryId)
            </div>

            <div class="editor-field">
                <label>Nhà sản xuất</label>
                @Html.DropDownList("PublisherId", String.Empty)
                @Html.ValidationMessageFor(model => model.PublisherId)
            </div>
            <div class="editor-field">
                <label>Hình ảnh</label>
                <input type="file" name="file" />
            </div>
            <div class="button-field">
                <input type="submit" value="Lưu" />
            </div>
        </fieldset>
}
        
<div class="back-function">
    @Html.ActionLink("Quay trở lại trang quản lý", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

CShop/Views/Product/Index.cshtml
@model IEnumerable<WebApplication1.ModelsTest.Product>

@{
    ViewBag.Title = "Index";
}
@section Styles{
<link href="~/Content/product.css" rel="stylesheet" />
}

<h2 id="add-product">
    <a href="@Url.Action("Create", "Product")">
        <img src="~/Images/new_button.png" />
    </a>
    @Html.ActionLink("Thêm mới", "Create")
</h2>

@using (Html.BeginForm("ViewByType", "Product"))
{

    <table>
        <tr>
            <th>
                @Html.ActionLink("Tên sản phẩm", "ViewByType", new { sortOrder = ViewBag.NameSortParm })
            </th>
            <th>
                @Html.ActionLink("Giá tiền", "ViewByType", new { sortOrder = ViewBag.CostSortParm })
            </th>
            <th>
                Chi tiết
            </th>
            <th>
                @Html.ActionLink("Tình trạng", "ViewByType", new { sortOrder = ViewBag.StatusSortParm })

            </th>
            <th>
                Loại sản phẩm
            </th>
            <th>
                Nhà sản xuất
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Detail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Publisher.Name)
                </td>
                <td>
                    @Html.ActionLink("Sửa", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Chi tiết", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Xóa", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>

    
}

CShop/Views/Product/PagingPartial.cshtml
@if (ViewBag.Comments != null)
{
    foreach (var cm in ViewBag.Comments)
    {
        <div class="comment-box-user" data-postid="@cm.Id">
            <div class="comment-box-username">@cm.SenderName</div>
            <div class="comment-box-text">@cm.Content</div>
            <div class='comment-function edit-function'>Sửa | </div>
            <div class='comment-function delete-function'>Xóa</div>
        </div>
    }
}

<div class="pageNumber">
    @{
        int count = ViewBag.Comments.TotalItemCount / ViewBag.Comments.PageSize;
        int x = ViewBag.Comments.TotalItemCount % ViewBag.Comments.PageSize;
        if (x > 0)
        {
            count = count + 1;
        }
        for (int i = 0; i < count; i++)
        {
            <a id="@(i+1)" name="@ViewBag.Comments.PageSize" class="pageComment">@(i + 1)</a>
        }
    }
</div>